### ISSUE TITLE
Doubt regarding evaluation

### ISSUE THREAD

**Issue by manigalati** [CRazorback/AADG#11]
Hello! :)

First of all, thank you for sharing the code of your work. It's really useful!

I have a question regarding your experiments. I have noticed from your ".yaml" files that you often run your code with K=3 source TRAIN datasets, and you leave one out as TEST. This TEST domain is your target domain, and you use it at evaluation time, to calculate metrics and save the best checkpoint. Are my suppositions correct?

**Comment by manigalati** [comment]
The doubt comes from the fact that I always see the target domain as something that is seen only at inference, i.e., after training. However, the TEST path is invoked already by the training code in this case, am I right?

**Comment by CRazorback** [comment]
Hi,

Thank you for your interest in our work. Practically, the target domain should not be available for validation. We use it during evaluation in order to fairly compare with previous SOTA methods such as DoFE, as presented in their codes. The most rigorous way is to choose the last epoch as the final model for evaluation, where AADG will deliver a similar performance.

**Comment by manigalati** [comment]
Understood, thanks! :)
Can I ask one more question? Does it have any repercussion on your model to train with unbalanced data, i.e., a significantly different number of training data for each source domain?

**Comment by CRazorback** [comment]
Yes. We evaluated AADG for retinal lesion segmentation on three publicly-available datasets of IDRiD, E-Ophtha, and DDR. The sample size is respective 81, 82, and 757. The improvement is even more significant (45.88 -> 49.77) since the baseline model tends to overfit the dataset with more samples.
